"""Discrete dynamical systems and coupling learning on the IVM lattice.

Scalar fields evolve over integer sites of the IVM lattice graph built
from canonical quadray representatives (Fuller.4D; see `quadray.py`).
The module provides:

- lattice construction: `ball_sites`, `make_lattice` — the finite ball of
  canonical quadray sites with edges given by the 12-around-one IVM
  neighbor shifts (all permutations of (2, 1, 1, 0));
- updates: `heat_step` (symmetric-normalized diffusion, provably
  non-increasing in sum-of-squares for every coupling in [0, 1]) and
  `majority_step` (rounded neighbor averaging on integer states,
  provably range-preserving; NOT claimed sum-of-squares monotone);
- simulation: `step`, `simulate(T, params)` — deterministic given the
  fixed seed in `DynamicsParams`;
- learning: `fit_trajectory(observed, grid, ...)` — gradient-free grid
  search with coordinate refinement minimizing trajectory MSE;
- honest observables: `sum_of_squares`, `is_nonincreasing`; the exact
  per-step monotonicity claims are tested in `tests/test_ivm_dynamics.py`.

Only numpy (plus `quadray`) is imported at module level; matplotlib and
`paths` are imported lazily inside `render_dynamics_demo`.
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from itertools import permutations
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

from quadray import DEFAULT_EMBEDDING, Quadray, to_xyz


def neighbor_shifts() -> List[Quadray]:
    """Return the 12 canonical IVM neighbor shifts as quadray deltas.

    The move set is all distinct permutations of (2, 1, 1, 0). Under
    `DEFAULT_EMBEDDING` each shift has integer squared radius 8, i.e. the
    close-packing (sphere-touching) distance of the 12-around-one cluster.
    """
    base = (2, 1, 1, 0)
    uniq = sorted(set(permutations(base)))
    return [Quadray(*u) for u in uniq]


def site_radius_sq(q: Quadray) -> int:
    """Integer squared IVM radius of a quadray site (squared embedding norm).

    Parameters
    - q: quadray site (any representative; the value is invariant under
      (1,1,1,1) shifts because that vector lies in the embedding kernel).

    Returns
    - int: squared Euclidean norm of the embedded site.
    """
    x, y, z = to_xyz(q, DEFAULT_EMBEDDING)
    return int(round(x * x + y * y + z * z))


def ball_sites(radius: int) -> List[Quadray]:
    """Enumerate canonical quadray sites with squared IVM radius <= radius**2.

    Sites are canonical quadray representatives: non-negative integer
    components with at least one zero. For a canonical nonzero site the
    squared radius is at least twice the square of its largest component,
    so enumerating components in [0, radius] covers the whole ball.

    Parameters
    - radius: inclusive radius bound; must be non-negative.

    Returns
    - List[Quadray]: sites sorted by (squared radius, components) for
      deterministic ordering.
    """
    if radius < 0:
        raise ValueError("radius must be non-negative")
    r_cap = radius * radius
    found: List[Tuple[int, Tuple[int, int, int, int]]] = []
    for a in range(radius + 1):
        for b in range(radius + 1):
            for c in range(radius + 1):
                for d in range(radius + 1):
                    q = Quadray(a, b, c, d)
                    if min(q.as_tuple()) != 0:
                        continue  # keep canonical representatives only
                    r2 = site_radius_sq(q)
                    if r2 <= r_cap:
                        found.append((r2, q.as_tuple()))
    found.sort()
    return [Quadray(*t) for _, t in found]


@dataclass(frozen=True)
class IVMLattice:
    """Finite IVM lattice ball with neighbor adjacency and diffusion operators.

    - adjacency: (N, N) 0/1 matrix; edge iff one IVM neighbor shift maps
      one site onto the other (canonical renormalization does not move the
      embedded point).
    - degrees: (N,) neighbor counts; boundary/isolated sites may be 0.
    - diffusion: S = D^{-1/2} A D^{-1/2} with zero rows for isolated
      sites; symmetric with spectrum in [-1, 1] (basis of the heat lemma).
    - average: row-stochastic plain neighbor average P; identity row for
      isolated sites.
    """

    radius: int
    sites: Tuple[Quadray, ...]
    adjacency: np.ndarray
    degrees: np.ndarray
    diffusion: np.ndarray
    average: np.ndarray

    @property
    def size(self) -> int:
        """Number of lattice sites."""
        return len(self.sites)


def make_lattice(radius: int) -> IVMLattice:
    """Build the finite IVM lattice ball of the given radius.

    The move graph may decompose into several connected components (cosets
    of the lattice generated by the neighbor shifts); the component of the
    origin is the 12-around-one close-packing cluster.
    """
    sites = tuple(ball_sites(radius))
    n = len(sites)
    index = {q.as_tuple(): i for i, q in enumerate(sites)}
    adjacency = np.zeros((n, n), dtype=np.uint8)
    for i, q in enumerate(sites):
        for shift in neighbor_shifts():
            j = index.get(q.add(shift).normalize().as_tuple())
            if j is not None:
                adjacency[i, j] = 1
    degrees = adjacency.sum(axis=1).astype(np.int64)
    deg_safe = np.maximum(degrees, 1).astype(float)
    inv_sqrt = np.where(degrees > 0, 1.0 / np.sqrt(deg_safe), 0.0)
    diffusion = adjacency.astype(float) * inv_sqrt[:, None] * inv_sqrt[None, :]
    average = adjacency.astype(float) / deg_safe[:, None]
    for i in np.flatnonzero(degrees == 0):
        average[i, i] = 1.0  # isolated sites hold their value
    return IVMLattice(
        radius=radius,
        sites=sites,
        adjacency=adjacency,
        degrees=degrees,
        diffusion=diffusion,
        average=average,
    )


def sum_of_squares(u: np.ndarray) -> float:
    """Sum of squares of a field — the observable of the heat lemma.

    Parameters
    - u: field values (any shape; flattened product with itself).

    Returns
    - float: <u, u>.
    """
    arr = np.asarray(u, dtype=float)
    return float(arr @ arr)


def is_nonincreasing(values: Sequence[float], tol: float = 1e-12) -> bool:
    """True iff no consecutive pair of values increases by more than tol.

    Parameters
    - values: sequence of observables (e.g. `Trajectory.sos`).
    - tol: tolerance absorbing floating-point round-off.

    Returns
    - bool: True iff values[t+1] <= values[t] + tol for all t.
    """
    for prev, nxt in zip(values, values[1:]):
        if nxt > prev + tol:
            return False
    return True


def _validated_field(u: np.ndarray, lattice: IVMLattice) -> np.ndarray:
    """Return the field as an array after shape validation."""
    arr = np.asarray(u)
    if arr.ndim != 1:
        raise ValueError("field must be one-dimensional")
    if arr.shape[0] != lattice.size:
        raise ValueError("field length must match lattice size")
    return arr


def _validated_alpha(alpha: float) -> float:
    """Validate and return the coupling parameter as a float."""
    value = float(alpha)
    if value < 0.0 or value > 1.0:
        raise ValueError("coupling alpha must lie in [0, 1]")
    return value


def heat_step(u: np.ndarray, lattice: IVMLattice, alpha: float) -> np.ndarray:
    """One heat-diffusion step u <- (1 - alpha) u + alpha S u.

    S = `lattice.diffusion` is the symmetric normalized adjacency with
    spectrum in [-1, 1], so the update operator (1 - alpha) I + alpha S has
    spectrum in [1 - 2 alpha, 1] subset [-1, 1] for alpha in [0, 1]; hence
    `sum_of_squares` is NON-INCREASING at every step, for any lattice and
    any state (lemma tested per step in the test suite). This guarantee is
    specific to the symmetric normalization S: plain row-average diffusion
    on truncated balls is NOT covered by the claim and is not used here.

    Parameters
    - u: 1-D field of length `lattice.size` (float values).
    - lattice: finite IVM lattice.
    - alpha: coupling in [0, 1] (0 = identity, 1 = pure diffusion).

    Returns
    - np.ndarray: updated float field.
    """
    arr = np.asarray(_validated_field(u, lattice), dtype=float)
    value = _validated_alpha(alpha)
    return arr + value * (lattice.diffusion @ arr - arr)


def majority_step(u: np.ndarray, lattice: IVMLattice, alpha: float) -> np.ndarray:
    """One rounded-averaging ("majority") step on integer states.

    u_next(s) = rint((1 - alpha) u(s) + alpha mean_{n in N(s)} u(n)), with
    identity rows for isolated sites and round-half-to-even ties. Every new
    value is a rounded convex combination of the site and its neighbors, so
    the field maximum is non-increasing and the minimum non-decreasing
    (range containment, tested per step). We deliberately do NOT claim
    sum-of-squares monotonicity here: rounding can increase it, and the
    test suite pins a demonstrating case.

    Parameters
    - u: 1-D integer-valued field of length `lattice.size`.
    - lattice: finite IVM lattice.
    - alpha: coupling in [0, 1] (0 = hold state, 1 = neighbor majority).

    Returns
    - np.ndarray: updated integer field.
    """
    arr = _validated_field(u, lattice)
    value = _validated_alpha(alpha)
    if not np.all(arr == np.rint(arr)):
        raise ValueError("majority update requires integer-valued states")
    blend = (1.0 - value) * arr + value * (lattice.average @ arr)
    return np.rint(blend).astype(np.int64)


@dataclass(frozen=True)
class DynamicsParams:
    """Parameters of a discrete IVM lattice dynamics run.

    - kind: "heat" (real-valued diffusion) or "majority" (integer rounded
      averaging).
    - alpha: coupling in [0, 1].
    - seed: RNG seed for synthetic initial fields (determinism contract).
    - radius: lattice ball radius used when no lattice is supplied.
    """

    kind: str = "heat"
    alpha: float = 0.35
    seed: int = 0
    radius: int = 3


def step(u: np.ndarray, lattice: IVMLattice, params: DynamicsParams) -> np.ndarray:
    """Apply one update of the dynamics in `params` to the field.

    Parameters
    - u: 1-D field of length `lattice.size`.
    - lattice: finite IVM lattice.
    - params: dynamics parameters (kind and coupling).

    Returns
    - np.ndarray: updated field (float for "heat", int for "majority").
    """
    if params.kind == "heat":
        return heat_step(u, lattice, params.alpha)
    if params.kind == "majority":
        return majority_step(u, lattice, params.alpha)
    raise ValueError(f"unknown dynamics kind: {params.kind!r}")


@dataclass
class Trajectory:
    """Deterministic simulation record.

    - fields: snapshots for t = 0..T (fields[0] is the initial state).
    - sos: `sum_of_squares` of each snapshot.
    """

    lattice: IVMLattice
    params: DynamicsParams
    fields: List[np.ndarray]
    sos: List[float]


def simulate(
    T: int,
    params: DynamicsParams,
    lattice: Optional[IVMLattice] = None,
    u0: Optional[np.ndarray] = None,
) -> Trajectory:
    """Simulate T updates; deterministic given `params` (fixed seed).

    With u0=None the initial field is drawn from numpy's seeded generator:
    uniform(-2, 2) floats for "heat", integers in [-3, 3] for "majority".
    T = 0 returns the initial field alone; T < 0 raises.

    Parameters
    - T: number of update steps (non-negative).
    - params: dynamics parameters (kind, alpha, seed, radius).
    - lattice: optional prebuilt lattice; defaults to make_lattice(params.radius).
    - u0: optional initial field overriding the seeded draw.

    Returns
    - Trajectory: fields and sum-of-squares for t = 0..T.
    """
    if T < 0:
        raise ValueError("horizon T must be non-negative")
    if lattice is None:
        lattice = make_lattice(params.radius)
    if u0 is None:
        rng = np.random.default_rng(params.seed)
        if params.kind == "heat":
            u0 = rng.uniform(-2.0, 2.0, size=lattice.size)
        else:
            u0 = rng.integers(-3, 4, size=lattice.size)
    arr = _validated_field(np.asarray(u0), lattice)
    fields: List[np.ndarray] = [arr]
    for _ in range(T):
        fields.append(step(fields[-1], lattice, params))
    return Trajectory(
        lattice=lattice,
        params=params,
        fields=fields,
        sos=[sum_of_squares(field) for field in fields],
    )


@dataclass(frozen=True)
class FitResult:
    """Outcome of gradient-free coupling identification.

    - best_alpha: coupling minimizing trajectory MSE over evaluated candidates.
    - best_mse: its mean squared error.
    - mses: every evaluated (candidate, mse) pair.
    - kind: dynamics kind used for re-simulation.
    """

    best_alpha: float
    best_mse: float
    mses: Dict[float, float]
    kind: str


def fit_trajectory(
    observed: np.ndarray,
    grid: Sequence[float],
    lattice: IVMLattice,
    kind: str = "heat",
    refine_rounds: int = 2,
) -> FitResult:
    """Identify the coupling alpha from an observed trajectory (gradient-free).

    `observed` has shape (T+1, N): row 0 is the initial condition, rows
    1..T the observed snapshots. Each candidate alpha in `grid` is scored
    by re-simulating from the initial condition and averaging the squared
    error against the observed snapshots; the best candidate is then
    refined by re-gridding the interval between its grid neighbors
    `refine_rounds` times (grid/coordinate search, no gradients). Ties
    resolve to the smallest alpha. The result is a global optimum over the
    evaluated candidates only; no convergence beyond refinement resolution
    is claimed.

    Parameters
    - observed: (T+1, N) snapshot matrix including the initial condition.
    - grid: candidate couplings, each in [0, 1]; must be non-empty.
    - lattice: lattice the observed snapshots live on.
    - kind: "heat" or "majority".
    - refine_rounds: number of interval re-gridding rounds (0 disables).

    Returns
    - FitResult: best coupling, its MSE, and the full MSE table.
    """
    grid_values = [float(g) for g in grid]
    if not grid_values:
        raise ValueError("grid must contain at least one candidate")
    obs = np.asarray(observed, dtype=float)
    if obs.ndim != 2 or obs.shape[0] < 2:
        raise ValueError("observed must have shape (T+1, N) with T >= 1")
    if obs.shape[1] != lattice.size:
        raise ValueError("observed width must match lattice size")
    for g in grid_values:
        if g < 0.0 or g > 1.0:
            raise ValueError("candidate couplings must lie in [0, 1]")
    horizon = obs.shape[0] - 1
    mses: Dict[float, float] = {}

    def _mse(alpha: float) -> float:
        if alpha not in mses:
            params = DynamicsParams(kind=kind, alpha=alpha)
            traj = simulate(horizon, params, lattice=lattice, u0=obs[0])
            pred = np.asarray(traj.fields[1:], dtype=float)
            mses[alpha] = float(np.mean((pred - obs[1:]) ** 2))
        return mses[alpha]

    candidates = sorted(set(grid_values))
    best = min(candidates, key=lambda g: (_mse(g), g))
    for _ in range(refine_rounds):
        i = candidates.index(best)
        lo = candidates[max(i - 1, 0)]
        hi = candidates[min(i + 1, len(candidates) - 1)]
        if lo == hi:
            break
        candidates = sorted(set(candidates) | set(np.linspace(lo, hi, 9).tolist()))
        best = min(candidates, key=lambda g: (_mse(g), g))
    return FitResult(best_alpha=best, best_mse=mses[best], mses=dict(mses), kind=kind)


def render_dynamics_demo(
    output_path: Optional[str] = None,
    *,
    radius: int = 3,
    seed: int = 7,
    alpha: float = 0.35,
    horizon: int = 40,
    fit_alpha: float = 0.3,
    grid_count: int = 21,
    refine_rounds: int = 2,
) -> str:
    """Render the multi-snapshot IVM dynamics demo figure; return its path.

    Panels: heat-field snapshots at t = 0, horizon//2, horizon over the
    embedded lattice; sum-of-squares histories for heat and majority
    updates; the `fit_trajectory` MSE landscape with best and true coupling;
    and the final majority (integer) field. Deterministic via fixed seeds.
    matplotlib and `paths` are imported lazily so the core module stays
    numpy-only.

    Parameters
    - output_path: target PNG path; defaults to
      quadmath/output/figures/ivm_dynamics_demo.png.
    - radius, seed, alpha, horizon: simulation parameters.
    - fit_alpha: true coupling of the synthetic trajectory to identify.
    - grid_count, refine_rounds: `fit_trajectory` search settings.

    Returns
    - str: path of the written figure.
    """
    import matplotlib.pyplot as plt

    from paths import get_figure_dir

    lattice = make_lattice(radius)
    heat = simulate(
        horizon, DynamicsParams(kind="heat", alpha=alpha, seed=seed), lattice
    )
    maj = simulate(
        horizon, DynamicsParams(kind="majority", alpha=alpha, seed=seed), lattice
    )
    observed = np.stack(
        simulate(
            horizon,
            DynamicsParams(kind="heat", alpha=fit_alpha, seed=seed),
            lattice,
            u0=heat.fields[0],
        ).fields
    )
    fit = fit_trajectory(
        observed, np.linspace(0.0, 1.0, grid_count), lattice, refine_rounds=refine_rounds
    )

    coords = np.array([to_xyz(q, DEFAULT_EMBEDDING) for q in lattice.sites])
    snapshot_times = (0, horizon // 2, horizon)
    values = [heat.fields[t] for t in snapshot_times]
    vmax = max(float(np.max(np.abs(v))) for v in values + [maj.fields[horizon]])
    fig = plt.figure(figsize=(13.5, 8.0))
    for k, (t, field) in enumerate(zip(snapshot_times, values)):
        ax = fig.add_subplot(2, 3, k + 1, projection="3d")
        ax.scatter(
            coords[:, 0],
            coords[:, 1],
            coords[:, 2],
            c=field,
            cmap="coolwarm",
            vmin=-vmax,
            vmax=vmax,
            s=28,
        )
        ax.set_title(f"heat field, t = {t}")
    ax = fig.add_subplot(2, 3, 4)
    ax.plot(range(horizon + 1), heat.sos, label="heat (lemma: non-increasing)")
    ax.plot(range(horizon + 1), maj.sos, label="majority (range-preserving)")
    ax.set_xlabel("t")
    ax.set_ylabel("sum of squares")
    ax.legend()
    ax.set_title("energy histories")
    ax = fig.add_subplot(2, 3, 5)
    alphas = sorted(fit.mses)
    ax.semilogy(alphas, np.maximum([fit.mses[a] for a in alphas], 1e-18), "o-", ms=3)
    ax.axvline(fit.best_alpha, color="k", ls="--", lw=1.0, label=f"fit {fit.best_alpha:.4f}")
    ax.axvline(fit_alpha, color="g", ls=":", lw=1.0, label=f"true {fit_alpha}")
    ax.set_xlabel("coupling alpha")
    ax.set_ylabel("trajectory MSE")
    ax.legend()
    ax.set_title("grid-search identification")
    ax = fig.add_subplot(2, 3, 6, projection="3d")
    ax.scatter(
        coords[:, 0],
        coords[:, 1],
        coords[:, 2],
        c=maj.fields[horizon],
        cmap="coolwarm",
        vmin=-vmax,
        vmax=vmax,
        s=28,
    )
    ax.set_title(f"majority field, t = {horizon}")
    fig.suptitle("IVM lattice dynamics: heat diffusion, majority rounding, coupling learning")
    fig.tight_layout()
    if output_path is None:
        target = os.path.join(get_figure_dir(), "ivm_dynamics_demo.png")
    else:
        target = output_path
    fig.savefig(target, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return target


__all__ = [
    "DynamicsParams",
    "FitResult",
    "IVMLattice",
    "Trajectory",
    "ball_sites",
    "fit_trajectory",
    "heat_step",
    "is_nonincreasing",
    "make_lattice",
    "majority_step",
    "neighbor_shifts",
    "render_dynamics_demo",
    "simulate",
    "site_radius_sq",
    "step",
    "sum_of_squares",
]